fix: NameError when importing SingleFileSnapshotExtension (#557)
If you try  to import `SingleFileSnapshotExtension` it will raise `NameError: name 'SerializedData' is not defined` because SerializedData is only imported if type checking and the return type annotation was not quoted.

Example:
```
>>> from syrupy.extensions.single_file import SingleFileSnapshotExtension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jocke/projects/syrupy/src/syrupy/extensions/single_file.py", line 26, in <module>
    class SingleFileSnapshotExtension(AbstractSyrupyExtension):
  File "/Users/jocke/projects/syrupy/src/syrupy/extensions/single_file.py", line 33, in SingleFileSnapshotExtension
    ) -> SerializedData:
NameError: name 'SerializedData' is not defined
```